<?php

/**
 * @file
 * SimpleAds Campaigns module.
 */

/**
 * Implements hook_menu().
 */
function simpleads_campaigns_menu() {
  $items = array();
  $items['admin/content/simpleads/create_campaign'] = array(
    'title' => 'Create new Ad Campaign',
    'page callback' => '_simpleads_campaign_new',
    'access callback' => '_simpleads_access_callback',
    'weight' => 17,
    'type' => MENU_LOCAL_ACTION,
  );
  return $items;
}

/**
 * Menu callback.
 * Redirect to SimpleAd Campiagn creation form.
 */
function _simpleads_campaign_new() {
  drupal_goto('node/add/simpleads-campaign', array('query' => array('destination' => 'admin/content/simpleads')));
}

/**
 * Implements hook_form_alter().
 */
function simpleads_campaigns_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'simpleads_node_form') {
    $lang = $form['language']['#value'];
    $campaigns = array(
      '_none' => t('- None -'),
    );
    $results = db_select('node', 'n')
      ->fields('n', array('title', 'nid'))
      ->condition('n.status', 1)
      ->condition('n.type', 'simpleads_campaign')
      ->condition('n.language', $lang)
      ->orderBy('n.title')
      ->execute();
    foreach ($results as $row) {
      $campaigns[$row->nid] = $row->title;
    }
    $node = FALSE;
    if (isset($form['#node']) && is_object($form['#node'])) {
      $node = $form['#node'];
    }
    if (isset($form['field_adcamp_list'])) {
      $form['field_adcamp_list'][$lang]['#prefix'] = '<div style="display:none;">';
      $form['field_adcamp_list'][$lang]['#suffix'] = '</div>';
      $title = $form['field_adcamp_list'][$lang][0]['#title'];
      $description = $form['field_adcamp_list'][$lang][0]['#description'];
      $default = "";
      if ($node && isset($node->field_adcamp_list[$node->language]) && !empty($node->field_adcamp_list[$node->language][0]['safe_value'])) {
        $default = $node->field_adcamp_list[$node->language][0]['safe_value'];
      }
      $form['campaign'] = array(
        '#type' => 'select',
        '#title' => $title,
        '#description' => $description,
        '#weight' => 9,
        '#options' => $campaigns,
        '#default_value' => $default,
      );
    }
  }
}

/**
 * Implements hook_node_presave().
 */
function simpleads_campaigns_node_presave($node) {
  if ($node->type == 'simpleads' && isset($node->campaign)) {
    $node->field_adcamp_list[$node->language][0]['value'] = $node->campaign;
  }
}

/**
 * Implements hook_node_access().
 */
function simpleads_campaigns_node_access($node, $op, $account) {
  if (isset($node->type) && $node->type == 'simpleads_campaign' && $op == 'view' && !user_access('administer nodes', $account)) {
    return NODE_ACCESS_DENY;
  }
}

/**
 * Implements hook_simpleads_preload().
 */
function simpleads_campaigns_simpleads_preload($nid) {
  _simpleads_campaigns_watch();
}

/**
 * Implements hook_simpleads_ad_click().
 */
function simpleads_campaigns_simpleads_ad_click($op, $nid) {
  if ($op == 'insert') {
    _simpleads_campaigns_watch();
  }
}

/**
 * Implements hook_simpleads_ad_impression().
 */
function simpleads_campaigns_simpleads_ad_impression($op, $nid) {
  if ($op == 'insert') {
    _simpleads_campaigns_watch();
  }
}

/**
 * Implements hook_cron().
 */
function simpleads_campaigns_cron() {
  _simpleads_campaigns_watch();
}

/**
 * Helper function.
 * Timestamp to days.
 */
function _simpleads_campains_date_diff($node) {
  $start_time = "";
  $end_time = "";

  if (isset($node->field_ad_start_date[$node->language]) && !empty($node->field_ad_start_date[$node->language][0]['value'])) {
    $start_time = $node->field_ad_start_date[$node->language][0]['value'];
  }

  $ustart_time = strtotime($start_time);
  $uend_time = REQUEST_TIME;
  $now = time();

  if ($ustart_time == '' && $uend_time != '') {
    return floor(($uend_time - $now) / 86400);
  }
  elseif ($ustart_time != '' && $uend_time != '') {
    return floor(($uend_time - $ustart_time) / 86400);
  }
  elseif ($ustart_time == '' && $uend_time == '') {
    return FALSE;
  }
  else {
    return 0;
  }
}

/**
 * Helper function.
 */
function _simpleads_campaigns_watch() {
  module_load_include('inc', 'simpleads', 'simpleads.stat');
  $results = db_select('node', 'n')
    ->fields('n', array('nid'))
    ->condition('n.status', 1)
    ->condition('n.type', 'simpleads_campaign')
    ->orderBy('n.title')
    ->execute();
  foreach ($results as $row) {
    $campaign = node_load($row->nid);
    $query = db_select('node', 'n');
    $query->join('field_data_field_adcamp_list', 'l', 'l.entity_id = n.nid AND l.revision_id = n.vid');
    $query->fields('n', array('nid'));
    $query->condition('n.status', 1)
      ->condition('n.type', 'simpleads')
      ->condition('l.field_adcamp_list_value', $row->nid)
      ->orderBy('n.title');

    $by_impressions = FALSE;
    $impressions_number = "";
    $by_clicks = FALSE;
    $clicks_number = "";
    $by_days = FALSE;
    $days_number = "";

    if (isset($campaign->field_adcamp_impression[$campaign->language]) && $campaign->field_adcamp_impression[$campaign->language][0]['value'] == 1) {
      $by_impressions = TRUE;
      if (isset($campaign->field_adcamp_impressions[$campaign->language]) && !empty($campaign->field_adcamp_impressions[$campaign->language][0]['safe_value'])) {
        $impressions_number = $campaign->field_adcamp_impressions[$campaign->language][0]['safe_value'];
      }
    }

    if (isset($campaign->field_adcamp_click[$campaign->language]) && $campaign->field_adcamp_click[$campaign->language][0]['value'] == 1) {
      $by_clicks = TRUE;
      if (isset($campaign->field_adcamp_clicks[$campaign->language]) && !empty($campaign->field_adcamp_clicks[$campaign->language][0]['safe_value'])) {
        $clicks_number = $campaign->field_adcamp_clicks[$campaign->language][0]['safe_value'];
      }
    }

    if (isset($campaign->field_adcamp_day[$campaign->language]) && $campaign->field_adcamp_day[$campaign->language][0]['value'] == 1) {
      $by_days = TRUE;
      if (isset($campaign->field_adcamp_days[$campaign->language]) && !empty($campaign->field_adcamp_days[$campaign->language][0]['safe_value'])) {
        $days_number = $campaign->field_adcamp_days[$campaign->language][0]['safe_value'];
      }
    }

    $ads = $query->execute();
    foreach ($ads as $ad) {
      $clicks = _simpleads_get_statistics('simpleads_clicks', $ad->nid);
      $impressions = _simpleads_get_statistics('simpleads_impressions', $ad->nid);
      $all_clicks = explode('/', $clicks['All Time']);
      $all_impressions = explode('/', $impressions['All Time']);
      $node = node_load($ad->nid);
      $days_left = _simpleads_campains_date_diff($node);
      if ($by_impressions && $by_clicks && $by_days) {
        if ($all_impressions[1] >= $impressions_number || $all_clicks[1] >= $clicks_number || $days_left >= $days_number) {
          $node->status = 0;
          $node->field_ad_status[$node->language][0]['value'] = 0;
          node_save($node);
        }
      }
      elseif ($by_impressions && $by_clicks && !$by_days) {
        if ($all_impressions[1] >= $impressions_number || $all_clicks[1] >= $clicks_number) {
          $node->status = 0;
          $node->field_ad_status[$node->language][0]['value'] = 0;
          node_save($node);
        }
      }
      elseif ($by_impressions && !$by_clicks && !$by_days) {
        if ($all_impressions[0] >= $impressions_number) {
          $node->status = 0;
          $node->field_ad_status[$node->language][0]['value'] = 0;
          node_save($node);
        }
      }
    }
  }
}